### ISSUE TITLE
Example for JsonGetFieldAsText

### ISSUE THREAD

**Issue by steevanb** [martin-georgiev/postgresql-for-doctrine#16]
Hi,

Could you please give me an example in Doctrine for this SQL query :
```
SELECT id, title
FROM my_table
where title->>'fr' like '%AAA%';
```
I've tried some syntaxe in DQL, but i don't find a way to use it.

**Comment by martin-georgiev** [comment]
The exact DQL will depend on how `JsonGetFieldAsText` is registered in your project. Presuming you registered it after the `README` example your DQL would probably read:
```dql
SELECT entity
FROM MyTableEntity entity
WHERE JSONB_EXISTS(entity.title, 'fr') LIKE '%AAA%'
```

**Comment by steevanb** [comment]
It doesn't work, here is my configuration :
```yml
doctrine:
    orm:
        entity_managers:
            default:
                dql:
                    string_functions:
                        JSONB_EXISTS: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonbExists
```
And this QueryBuilder :
```php
$this
    ->createQueryBuilder('page')
    ->join('page.category', 'category')
    ->where('JSONB_EXISTS(page.url, \'' . $locale . '\') = :slug')
    ->setParameter('slug', $slug)
    ->getQuery()
    ->getOneOrNullResult();
```
I got thie error :
`function jsonb_exists(json, unknown) does not exist`

I don't undertand where i miss something ?
