### ISSUE TITLE
How to use with inet[] and cidr[] types?

### ISSUE THREAD

**Issue by RinkAttendant6** [martin-georgiev/postgresql-for-doctrine#260]
I'm trying to use this package to map [`inet[]` and `cidr[]` types](https://www.postgresql.org/docs/current/datatype-net-types.html) properly but I can't seem to get it working.

I tried adding the following into my Symfony config/doctrine.yaml:

```yaml
doctrine:
  dbal:
    # ...
    types:
      # ...all the other types
      inet[]: MartinGeorgiev\Doctrine\DBAL\Types\TextArray
      cidr[]: MartinGeorgiev\Doctrine\DBAL\Types\TextArray
    mapping_types:
      # ...all the other types
      inet[]: text[]
      _inet: text[]
      cidr[]: text[]
      _cidr: text[]
```

It doesn't change how the value is returned. What am I doing wrong?
