### ISSUE TITLE
Invalid integration doc for symfony

### ISSUE THREAD

**Issue by alexandrmazur96** [martin-georgiev/postgresql-for-doctrine#32]
Hi guys! 

In your doc, described integration with symfony you write:

```
doctrine:
    orm:
        entity_managers:
            your_connection:
                dql:
                    string_functions:
                        # alternative implementation of ALL() and ANY() where subquery is not required, useful for arrays
                        ALL_OF: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\All
                        ANY_OF: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Any
```

But this not working for symfony 4.*

I solved the problem via:

``` 
doctrine:
    orm:
        dql:
            string_functions:
                PG_ALL: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\All
                PG_ANY: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Any
```

Check this, maybe for different connection need other config, but your config not working with default connection.
