### ISSUE TITLE
Symfony5 Error: Class 'jsonb_each_text' is not defined.

### ISSUE THREAD

**Issue by shubaivan** [martin-georgiev/postgresql-for-doctrine#60]
I installed bundle and after try to execute simple query faced with error. What's wrong with my configuration ? 

```
doctrine:
    dbal:
        types:
            jsonb: MartinGeorgiev\Doctrine\DBAL\Types\Jsonb
            jsonb[]: MartinGeorgiev\Doctrine\DBAL\Types\JsonbArray
        mapping_types:
            jsonb: jsonb
            jsonb[]: jsonb[]
        schema_filter: '~^(?!messenger_messages)~'
        driver: 'pdo_pgsql'
        server_version: '9.6'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        dql:
            string_functions:
                JSONB_EACH_TEXT: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonbEachText

        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

query

        $query = $entityManager
            ->createQuery("
        SELECT p
        FROM App:Product p
        JOIN jsonb_each_text(p.extras) e on true
        WHERE e.value = 'world'
        ");

[Semantical Error] line 0, col 58 near 'jsonb_each_text(p.extras)': Error: Class 'jsonb_each_text' is not defined.
