### ISSUE TITLE
jsonb type is interpreted as json in doctrine migrations

### ISSUE THREAD

**Issue by vbourdeix** [martin-georgiev/postgresql-for-doctrine#71]
When creating an entity with a jsonb field and generating a migration with doctrine migrations, the migration defines the field as JSON, which forces me to fix that mannually each time I create a migration.

Do you have a way to fix this ?

**Comment by martin-georgiev** [comment]
Sounds like something is missing from the configuration. Can you share your setup, please?

**Comment by vbourdeix** [comment]
Here is my config/packages/doctrine.yaml :
```
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: en_US.UTF-8

        url: '%env(resolve:DATABASE_URL)%'
        types:
            jsonb: MartinGeorgiev\Doctrine\DBAL\Types\Jsonb
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

        dql:
            string_functions:
                ILIKE: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Ilike
                CONTAINS: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Contains
                JSON_GET_FIELD: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonGetField
```

Did I miss something ?

**Comment by martin-georgiev** [comment]
Did you find what's the problem?

**Comment by Aweptimum** [comment]
I tried reproducing this behavior while installing the package. Noticed that the `mapping_types` section is missing from @vbourdeix's doctrine config, so I omitted it and the migration does indeed default to json. Adding the following to `doctrine.yaml` fixes it
```yaml
    dbal:
        mapping_types:
            jsonb: jsonb 
```
